[pytest]
markers =
   soma: testes de soma
   sub: testes de subtracao
   mult: testes de multiplicacao
   div: testes de divisao
   resto: testes de resto
   pot: testes de potencia
   raiz: testes de raiz